name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger interscript-api
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: phuonghuynh/testci2
          event-type: ${{ github.repository }}
          client-payload: '{ "ref": "${{ github.ref }}" }'
