name: terraform

on:
  repository_dispatch:
    types: [ phuonghuynh/testci2 ]

env:
  GITHUB_PUSH_TOKEN: ${{ secrets.MY_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  RUN_ID: ${{github.workflow}}#${{github.run_number}}

jobs:
  run-terraform:
    runs-on: ubuntu-18.04
    if: github.event.client_payload.workflow == 'terraform'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.29

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Apply
        run: |
          terraform init
          terraform workspace select prod
          terraform apply -auto-approve --var-file terraform.tfstate.d/prod/terraform.tfvars

      - name: Push changes to new branch
        uses: EndBug/add-and-commit@v5.2.0 # You can change this to use a specific version
        with:
          branch: "gha/${{env.RUN_ID}}"
          message: '[bot] Update terraform state file for runner ${{github.workflow}}#${{github.run_number}}'
          signoff: true

      - name: Send PR to update statefile
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "gha/${{env.RUN_ID}}"
          destination_branch: "main"
          pr_title: "[bot] Update terraform.tfstate into main"
          pr_body: "https://${{github.repository}}/actions/runs/${{github.run_number}}"
