name: terraform

on:
  repository_dispatch:
    types: [ phuonghuynh/testci2 ]

env:
  GITHUB_PUSH_TOKEN: ${{ secrets.MY_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  RUN_ID: ${{github.workflow}}#${{github.run_number}}
  INTERSCRIPT_VERSION: ${{github.event.client_payload.interscript_version}}

jobs:
  run-terraform:
    runs-on: ubuntu-18.04
    if: github.event.client_payload.workflow == 'terraform'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.29

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Apply
        run: |
          terraform init
          terraform workspace select prod
          terraform apply -auto-approve --var-file terraform.tfstate.d/prod/terraform.tfvars

      - name: Push changes to git
        run: |
          git checkout -b ${{env.RUN_ID}}
          git add .
          git commit -m "[bot] Auto deployed interscript v${{env.INTERSCRIPT_VERSION}}"
          git push origin ${{env.RUN_ID}}

#      - name: Push changes to current branch
#        id: push_current
#        uses: EndBug/add-and-commit@v5.2.0 # You can change this to use a specific version
#        with:
#          message: '[bot] Auto deployed interscript v${{env.INTERSCRIPT_VERSION}}'
#          signoff: true
#        continue-on-error: true
#
#      - name: Create new branch to push changes
#        if: steps.push_current.outcome == 'failure'
#        uses: peterjgrainger/action-create-branch@v2.0.1
#        with:
#          branch: 'gha/${{env.RUN_ID}}'
#      - name: Send PR to update statefile
#        if: steps.push_current.outcome == 'failure'
#        uses: repo-sync/pull-request@v2
#        with:
#          destination_branch: "main"
#          pr_title: "[bot] Update terraform.tfstate into main for interscript v${{env.INTERSCRIPT_VERSION}}"
#          pr_body: "https://${{github.repository}}/actions/runs/${{github.run_number}}"
