name: terraform

on:
  repository_dispatch:
    types: [ phuonghuynh/testci2 ]

env:
  INTERSCRIPT_VERSION: ${{github.event.client_payload.interscript_version}}
  TF_VAR_interscript_version: ${{github.event.client_payload.interscript_version}}
  GITHUB_PUSH_TOKEN: ${{ secrets.MY_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  PUSH_BRANCH: gha/${{github.workflow}}#${{github.run_id}}
  RUN_URL: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

jobs:
  run-terraform:
    runs-on: ubuntu-18.04
    if: github.event.client_payload.workflow == 'terraform'
    steps:
      - uses: actions/checkout@v2

      - name: Prepare env
        run: |
          echo "PR_REVIEWERS=$(cat .github/.pr_reviewers)" >> ${GITHUB_ENV}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.29

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Apply
        run: |
          terraform init
          terraform workspace select prod
          terraform apply -auto-approve --var-file terraform.tfstate.d/prod/terraform.tfvars

      # get GHA email from https://github.community/t/github-actions-bot-email-address/17204/5
      - name: Push changes to git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b ${{env.PUSH_BRANCH}}
          git add .
          git commit -m "[bot] Auto deployed interscript v${{env.INTERSCRIPT_VERSION}}"
          git push origin ${{env.PUSH_BRANCH}}

      - name: Send PR to update statefile
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{env.PUSH_BRANCH}}
          destination_branch: "main"
          pr_reviewer: ${{env.PR_REVIEWERS}}
          pr_assignee: ${{env.PR_REVIEWERS}}
          pr_label: "terraform"
          pr_title: "[bot] Update terraform.tfstate into main for interscript v${{env.INTERSCRIPT_VERSION}}"
          pr_body: "Console log can be view [here](${{env.RUN_URL}})"
